# -*- coding: utf-8 -*-
"""ArthVratta_Colab.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1z491kceT3J60Lu4ay47gCQrwznY5Gjoi

# 🌾 ArthVratta - The Financial Resilience Farm
## Grow Your Financial Future, One Season at a Time

A voice-first, narrative-driven farming simulation game that teaches financial literacy through agricultural gameplay.

---

### 📋 Features:
- **Multi-User Support**: Farmers, Women, Students, Young Adults
- **Seasonal Gameplay**: Kharif, Rabi, Zaid seasons with unique challenges
- **Financial Concepts**: Savings, Insurance, Emergency Fund, Risk Management
- **Dynamic Events**: Droughts, Market Booms, Scams, Health Emergencies
- **Resilience Score**: Real-time financial health tracking

---

## Step 1: Install Required Dependencies

Run this cell to install Gradio and other required packages.
"""

# Install required packages
!pip install -q gradio pandas

"""## Step 2: Import Libraries"""

import gradio as gr
import json
import random
from datetime import datetime
from typing import Dict, List, Tuple
import pandas as pd

print("✅ All libraries imported successfully!")

"""## Step 3: Game Engine Class

The core game logic implementing all financial literacy mechanics.
"""

class ArthVrattaGame:
    """Main game engine for ArthVratta financial farming simulation"""

    def __init__(self):
        self.reset_game()

    def reset_game(self):
        """Initialize or reset game state"""
        self.game_state = {
            "player_name": "",
            "user_type": "",  # farmer, woman, student, young_adult
            "season": "kharif",  # kharif, rabi, zaid
            "season_number": 1,
            "money": 10000,
            "savings": 0,
            "debt": 0,
            "crops": [],
            "insurance": {
                "crop_insurance": False,
                "health_insurance": False
            },
            "emergency_fund": 0,
            "resilience_score": 50,
            "inventory": {
                "seeds": 100,
                "fertilizer": 50,
                "water": 100
            },
            "knowledge_points": 0,
            "completed_missions": [],
            "farm_health": "moderate"
        }
        self.history = []
        self.current_event = None

    def calculate_resilience_score(self) -> int:
        """Calculate financial resilience score (0-100)"""
        score = 0

        # Savings ratio (30 points max)
        total_assets = self.game_state["money"] + self.game_state["savings"]
        if total_assets > 0:
            savings_ratio = self.game_state["savings"] / total_assets
            score += min(30, savings_ratio * 100)

        # Debt load (20 points max)
        if self.game_state["debt"] == 0:
            score += 20
        elif total_assets > 0:
            debt_ratio = self.game_state["debt"] / total_assets
            score += max(0, 20 - (debt_ratio * 20))

        # Insurance coverage (20 points max)
        if self.game_state["insurance"]["crop_insurance"]:
            score += 10
        if self.game_state["insurance"]["health_insurance"]:
            score += 10

        # Emergency fund (20 points max)
        if self.game_state["emergency_fund"] >= 5000:
            score += 20
        else:
            score += (self.game_state["emergency_fund"] / 5000) * 20

        # Diversification (10 points max)
        crop_diversity = len(set([crop["type"] for crop in self.game_state["crops"]]))
        score += min(10, crop_diversity * 3)

        return int(score)

    def get_farm_health_status(self, score: int) -> str:
        """Convert resilience score to farm health description"""
        if score >= 80:
            return "🌾 Lush Green Fields - Excellent Financial Health!"
        elif score >= 60:
            return "🌱 Growing Well - Good Financial Health"
        elif score >= 40:
            return "🍂 Moderate Growth - Fair Financial Health"
        elif score >= 20:
            return "🥀 Struggling Crops - Poor Financial Health"
        else:
            return "🪦 Withered Fields - Critical Financial Situation"

    def start_game(self, name: str, user_type: str) -> str:
        """Initialize game with player details"""
        self.game_state["player_name"] = name
        self.game_state["user_type"] = user_type

        intro_messages = {
            "farmer": f"Welcome, {name}! 🚜 You inherit a small farm with ₹10,000. Your goal: Build financial resilience through smart farming decisions.",
            "woman": f"Namaste, {name}! 👩‍🌾 You're starting a farming enterprise while managing household finances. Balance both to prosper!",
            "student": f"Hello, {name}! 📚 Learn money management through your pocket money garden. Small decisions, big lessons!",
            "young_adult": f"Hey, {name}! 💼 Build your agri-startup from scratch. Learn investment, insurance, and business finance!"
        }

        return intro_messages.get(user_type, f"Welcome, {name}! Let's begin your financial farming journey.")

    def get_season_info(self) -> str:
        """Get current season information"""
        season_info = {
            "kharif": "🌧️ **Kharif Season (Monsoon)** - Time to invest in crops! Plan your budget wisely.",
            "rabi": "☀️ **Rabi Season (Winter)** - Harvest time! Manage your income and save for the future.",
            "zaid": "🌞 **Zaid Season (Summer)** - Lean period. Test your emergency fund and savings!"
        }
        return season_info.get(self.game_state["season"], "")

    def plant_crop(self, crop_type: str, investment: int) -> str:
        """Plant a crop with given investment"""
        crop_costs = {
            "rice": 1000,
            "wheat": 800,
            "vegetables": 500,
            "pulses": 700,
            "cash_crop": 1500
        }

        cost = crop_costs.get(crop_type, 1000)

        if investment < cost:
            return f"❌ Insufficient investment! {crop_type.title()} requires at least ₹{cost}"

        if self.game_state["money"] < investment:
            return f"❌ Insufficient funds! You only have ₹{self.game_state['money']}"

        # Deduct money and plant crop
        self.game_state["money"] -= investment

        crop = {
            "type": crop_type,
            "investment": investment,
            "season_planted": self.game_state["season_number"],
            "insured": self.game_state["insurance"]["crop_insurance"]
        }

        self.game_state["crops"].append(crop)

        return f"✅ Planted {crop_type.title()}! Investment: ₹{investment}. Remaining balance: ₹{self.game_state['money']}"

    def buy_insurance(self, insurance_type: str) -> str:
        """Purchase insurance"""
        costs = {
            "crop": 500,
            "health": 800
        }

        cost = costs.get(insurance_type, 500)

        if self.game_state["money"] < cost:
            return f"❌ Insufficient funds! {insurance_type.title()} insurance costs ₹{cost}"

        self.game_state["money"] -= cost

        if insurance_type == "crop":
            self.game_state["insurance"]["crop_insurance"] = True
            return f"✅ Crop Insurance purchased! Cost: ₹{cost}. You're protected against crop failures!"
        elif insurance_type == "health":
            self.game_state["insurance"]["health_insurance"] = True
            return f"✅ Health Insurance purchased! Cost: ₹{cost}. Your family is protected!"

        return "❌ Invalid insurance type"

    def save_money(self, amount: int) -> str:
        """Move money to savings"""
        if amount <= 0:
            return "❌ Invalid amount"

        if self.game_state["money"] < amount:
            return f"❌ Insufficient funds! You only have ₹{self.game_state['money']}"

        self.game_state["money"] -= amount
        self.game_state["savings"] += amount

        return f"✅ Saved ₹{amount}! Total savings: ₹{self.game_state['savings']}"

    def build_emergency_fund(self, amount: int) -> str:
        """Add to emergency fund"""
        if amount <= 0:
            return "❌ Invalid amount"

        if self.game_state["money"] < amount:
            return f"❌ Insufficient funds! You only have ₹{self.game_state['money']}"

        self.game_state["money"] -= amount
        self.game_state["emergency_fund"] += amount

        return f"✅ Added ₹{amount} to Emergency Fund! Total: ₹{self.game_state['emergency_fund']}"

    def advance_season(self) -> str:
        """Move to next season and trigger events"""
        # Harvest crops if in rabi season
        harvest_message = ""
        if self.game_state["season"] == "rabi":
            harvest_message = self.harvest_crops()

        # Trigger random event
        event_message = self.trigger_random_event()

        # Advance season
        seasons = ["kharif", "rabi", "zaid"]
        current_idx = seasons.index(self.game_state["season"])
        next_idx = (current_idx + 1) % 3

        if next_idx == 0:
            self.game_state["season_number"] += 1

        self.game_state["season"] = seasons[next_idx]

        # Update resilience score
        self.game_state["resilience_score"] = self.calculate_resilience_score()
        self.game_state["farm_health"] = self.get_farm_health_status(self.game_state["resilience_score"])

        season_msg = self.get_season_info()

        return f"{harvest_message}\n\n{event_message}\n\n{season_msg}\n\n{self.game_state['farm_health']}"

    def harvest_crops(self) -> str:
        """Harvest all planted crops"""
        if not self.game_state["crops"]:
            return "No crops to harvest."

        total_yield = 0
        messages = ["🌾 **HARVEST TIME!**\n"]

        for crop in self.game_state["crops"]:
            # Calculate yield (1.5x to 2.5x investment based on luck)
            multiplier = random.uniform(1.5, 2.5)
            yield_amount = int(crop["investment"] * multiplier)
            total_yield += yield_amount

            messages.append(f"- {crop['type'].title()}: ₹{yield_amount} (from ₹{crop['investment']} investment)")

        self.game_state["money"] += total_yield
        self.game_state["crops"] = []  # Clear harvested crops

        messages.append(f"\n**Total Income: ₹{total_yield}**")
        messages.append(f"Current Balance: ₹{self.game_state['money']}")

        return "\n".join(messages)

    def trigger_random_event(self) -> str:
        """Trigger a random financial event"""
        events = [
            {
                "name": "drought",
                "description": "🌵 **DROUGHT ALERT!** Unexpected drought damaged crops.",
                "impact": lambda: self.handle_drought()
            },
            {
                "name": "family_illness",
                "description": "🏥 **FAMILY ILLNESS!** Medical emergency requires funds.",
                "impact": lambda: self.handle_illness()
            },
            {
                "name": "scam_attempt",
                "description": "📱 **SCAM ALERT!** Fake fertilizer seller sent QR code.",
                "impact": lambda: self.handle_scam()
            },
            {
                "name": "good_market",
                "description": "📈 **MARKET BOOM!** Prices increased by 20%!",
                "impact": lambda: self.handle_market_boom()
            },
            {
                "name": "no_event",
                "description": "✅ **PEACEFUL SEASON** - No major events.",
                "impact": lambda: "Continue farming wisely!"
            }
        ]

        # 60% chance of event, 40% chance of peaceful season
        if random.random() < 0.6:
            event = random.choice(events[:-1])
        else:
            event = events[-1]

        self.current_event = event
        impact_msg = event["impact"]()

        return f"{event['description']}\n{impact_msg}"

    def handle_drought(self) -> str:
        """Handle drought event"""
        if self.game_state["insurance"]["crop_insurance"]:
            compensation = 2000
            self.game_state["money"] += compensation
            return f"✅ Your Crop Insurance paid ₹{compensation}! You're protected."
        else:
            loss = min(3000, self.game_state["money"] // 2)
            self.game_state["money"] -= loss
            return f"❌ Lost ₹{loss}! Crop insurance could have prevented this."

    def handle_illness(self) -> str:
        """Handle family illness event"""
        medical_cost = 2500

        if self.game_state["insurance"]["health_insurance"]:
            self.game_state["money"] -= 500  # Small co-pay
            return f"✅ Health Insurance covered most costs! You paid only ₹500 co-pay."
        elif self.game_state["emergency_fund"] >= medical_cost:
            self.game_state["emergency_fund"] -= medical_cost
            return f"✅ Used Emergency Fund! Paid ₹{medical_cost} from savings."
        else:
            self.game_state["debt"] += medical_cost
            return f"❌ Took loan of ₹{medical_cost}! Health insurance would have helped."

    def handle_scam(self) -> str:
        """Handle scam attempt event"""
        return "⚠️ Never scan unknown QR codes! Always verify sellers. You avoided this scam! +50 Knowledge Points"

    def handle_market_boom(self) -> str:
        """Handle market boom event"""
        bonus = int(self.game_state["savings"] * 0.2)
        self.game_state["money"] += bonus
        return f"✅ Your savings grew! Earned ₹{bonus} from market boom."

    def get_dashboard(self) -> Dict:
        """Get current game dashboard"""
        return {
            "Player": self.game_state["player_name"],
            "User Type": self.game_state["user_type"].replace("_", " ").title(),
            "Season": f"{self.game_state['season'].title()} (Season {self.game_state['season_number']})",
            "Cash on Hand": f"₹{self.game_state['money']}",
            "Savings": f"₹{self.game_state['savings']}",
            "Emergency Fund": f"₹{self.game_state['emergency_fund']}",
            "Debt": f"₹{self.game_state['debt']}",
            "Crop Insurance": "✅ Yes" if self.game_state["insurance"]["crop_insurance"] else "❌ No",
            "Health Insurance": "✅ Yes" if self.game_state["insurance"]["health_insurance"] else "❌ No",
            "Resilience Score": f"{self.game_state['resilience_score']}/100",
            "Farm Health": self.game_state["farm_health"]
        }

    def get_financial_tips(self) -> str:
        """Get personalized financial tips based on current state"""
        tips = []

        if self.game_state["savings"] < 2000:
            tips.append("💡 Try to save at least 20% of your income each season")

        if not self.game_state["insurance"]["crop_insurance"] and self.game_state["money"] > 1000:
            tips.append("💡 Consider buying crop insurance to protect against losses")

        if not self.game_state["insurance"]["health_insurance"] and self.game_state["money"] > 1500:
            tips.append("💡 Health insurance can prevent debt from medical emergencies")

        if self.game_state["emergency_fund"] < 5000:
            tips.append("💡 Build an emergency fund of at least ₹5,000")

        if self.game_state["debt"] > 0:
            tips.append("💡 Focus on paying off debt to improve your resilience score")

        if len(self.game_state["crops"]) < 2:
            tips.append("💡 Diversify your crops to reduce risk")

        return "\n".join(tips) if tips else "✅ You're doing great! Keep up the good financial habits."

print("✅ ArthVrattaGame class loaded successfully!")

"""## Step 4: Initialize Game Instance"""

# Initialize game instance
game = ArthVrattaGame()
print("✅ Game instance created!")

"""## Step 5: Define Gradio Interface Functions"""

# Gradio Interface Functions
def start_new_game(name, user_type):
    """Start a new game"""
    game.reset_game()
    welcome_msg = game.start_game(name, user_type)
    season_info = game.get_season_info()
    dashboard = game.get_dashboard()

    return welcome_msg + "\n\n" + season_info, pd.DataFrame([dashboard]).T, game.get_financial_tips()

def plant_crop_action(crop_type, investment):
    """Plant crop action"""
    result = game.plant_crop(crop_type, int(investment))
    dashboard = game.get_dashboard()
    return result, pd.DataFrame([dashboard]).T, game.get_financial_tips()

def buy_insurance_action(insurance_type):
    """Buy insurance action"""
    result = game.buy_insurance(insurance_type)
    dashboard = game.get_dashboard()
    return result, pd.DataFrame([dashboard]).T, game.get_financial_tips()

def save_money_action(amount):
    """Save money action"""
    result = game.save_money(int(amount))
    dashboard = game.get_dashboard()
    return result, pd.DataFrame([dashboard]).T, game.get_financial_tips()

def emergency_fund_action(amount):
    """Add to emergency fund"""
    result = game.build_emergency_fund(int(amount))
    dashboard = game.get_dashboard()
    return result, pd.DataFrame([dashboard]).T, game.get_financial_tips()

def next_season_action():
    """Advance to next season"""
    result = game.advance_season()
    dashboard = game.get_dashboard()
    return result, pd.DataFrame([dashboard]).T, game.get_financial_tips()

print("✅ Interface functions defined!")

"""## Step 6: Create and Launch Gradio Interface"""

# Create Gradio Interface
with gr.Blocks(title="ArthVratta - Financial Resilience Farm", theme=gr.themes.Soft()) as demo:
    gr.Markdown("""
    # 🌾 ArthVratta - The Financial Resilience Farm
    ### Grow Your Financial Future, One Season at a Time

    **A farming simulation game that teaches financial literacy through agricultural gameplay.**
    Learn savings, budgeting, insurance, and digital finance through hands-on farming decisions!
    """)

    with gr.Row():
        with gr.Column(scale=1):
            gr.Markdown("### 🎮 Game Setup")
            player_name = gr.Textbox(label="Your Name", placeholder="Enter your name")
            user_type = gr.Radio(
                choices=["farmer", "woman", "student", "young_adult"],
                label="Select Your Role",
                value="farmer"
            )
            start_btn = gr.Button("🚀 Start Game", variant="primary")

    with gr.Row():
        with gr.Column(scale=2):
            game_output = gr.Textbox(label="📰 Game Updates", lines=8, interactive=False)

        with gr.Column(scale=1):
            dashboard = gr.Dataframe(label="📊 Financial Dashboard", interactive=False)

    tips_output = gr.Textbox(label="💡 Financial Tips", lines=3, interactive=False)

    gr.Markdown("---")
    gr.Markdown("### 🎯 Actions")

    with gr.Row():
        with gr.Column():
            gr.Markdown("#### 🌱 Plant Crops")
            crop_type = gr.Dropdown(
                choices=["rice", "wheat", "vegetables", "pulses", "cash_crop"],
                label="Crop Type",
                value="rice"
            )
            crop_investment = gr.Slider(
                minimum=500,
                maximum=5000,
                step=100,
                value=1000,
                label="Investment Amount (₹)"
            )
            plant_btn = gr.Button("🌾 Plant Crop", variant="secondary")

        with gr.Column():
            gr.Markdown("#### 🛡️ Buy Insurance")
            insurance_type = gr.Radio(
                choices=["crop", "health"],
                label="Insurance Type",
                value="crop"
            )
            insurance_btn = gr.Button("🛡️ Buy Insurance", variant="secondary")

    with gr.Row():
        with gr.Column():
            gr.Markdown("#### 💰 Save Money")
            save_amount = gr.Slider(
                minimum=100,
                maximum=5000,
                step=100,
                value=500,
                label="Amount to Save (₹)"
            )
            save_btn = gr.Button("💰 Save Money", variant="secondary")

        with gr.Column():
            gr.Markdown("#### 🏦 Emergency Fund")
            emergency_amount = gr.Slider(
                minimum=100,
                maximum=5000,
                step=100,
                value=500,
                label="Add to Emergency Fund (₹)"
            )
            emergency_btn = gr.Button("🏦 Build Emergency Fund", variant="secondary")

    gr.Markdown("---")
    next_season_btn = gr.Button("⏭️ Advance to Next Season", variant="primary", size="lg")

    # Event handlers
    start_btn.click(
        fn=start_new_game,
        inputs=[player_name, user_type],
        outputs=[game_output, dashboard, tips_output]
    )

    plant_btn.click(
        fn=plant_crop_action,
        inputs=[crop_type, crop_investment],
        outputs=[game_output, dashboard, tips_output]
    )

    insurance_btn.click(
        fn=buy_insurance_action,
        inputs=[insurance_type],
        outputs=[game_output, dashboard, tips_output]
    )

    save_btn.click(
        fn=save_money_action,
        inputs=[save_amount],
        outputs=[game_output, dashboard, tips_output]
    )

    emergency_btn.click(
        fn=emergency_fund_action,
        inputs=[emergency_amount],
        outputs=[game_output, dashboard, tips_output]
    )

    next_season_btn.click(
        fn=next_season_action,
        inputs=[],
        outputs=[game_output, dashboard, tips_output]
    )

    gr.Markdown("""
    ---
    ### 📚 How to Play:
    1. **Start the game** by entering your name and selecting your role
    2. **Plant crops** during Kharif season (invest wisely!)
    3. **Buy insurance** to protect against disasters
    4. **Save money** regularly to build financial resilience
    5. **Build emergency fund** for unexpected expenses
    6. **Advance seasons** to see your farm grow and face new challenges

    ### 🎓 Learn by Playing:
    - **Savings**: Build emergency fund and save regularly
    - **Insurance**: Protect against crop failure and health emergencies
    - **Budgeting**: Allocate resources across different crops
    - **Risk Management**: Diversify crops and prepare for events
    - **Financial Planning**: Plan for lean seasons and maximize harvests

    **Your Resilience Score shows your overall financial health!**
    """)

# Launch the interface
print("🚀 Launching ArthVratta Game...")
demo.launch(share=True, debug=True)

"""## 🎉 Game is Now Live!

The game interface should now be running above. You'll see:
- A local URL for testing
- A **public shareable URL** (ending in `.gradio.live`) that you can share with others

### Next Steps:
1. Enter your name and select your user type
2. Click "Start Game" to begin
3. Make financial decisions through farming gameplay
4. Watch your resilience score improve as you learn!

### Features Implemented:
✅ Multi-user support (Farmer, Woman, Student, Young Adult)  
✅ Three seasonal cycles (Kharif, Rabi, Zaid)  
✅ Crop planting and harvesting mechanics  
✅ Insurance system (Crop & Health)  
✅ Savings and Emergency Fund management  
✅ Random events (Droughts, Illness, Scams, Market Booms)  
✅ Financial Resilience Score calculation  
✅ Real-time dashboard tracking  
✅ Personalized financial tips  

---

**Developed for Financial Literacy through Gamification**  
*ArthVratta - Grow Your Financial Future, One Season at a Time* 🌾
''')
"""